### ISSUE TITLE
Change Channel port 

### ISSUE THREAD

**Issue by joanebrown** [walkor/Channel#1]
Hi,

I'm trying to change the port of Channel as follow:
```php

$channel = new \Channel\Server('127.0.0.1', 7596);

[...]

$io->on('workerStart', function()use($io) {
    echo "This message is show and then shows the error";
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
```
But I get the next error:

`Waring channel connection closed and try to reconnect`

When I trying to start the Workerman server.

**Comment by walkor** [comment]
https://github.com/walkor/phpsocket.io/issues/55
This may help you.

**Comment by joanebrown** [comment]
Yeah, this help me a lot! Now works :-)
